server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

zuul:
  routes:
    awesome-phrases:
      serviceId: awesome-phrases
  host:
    socket-timeout-millis: 30000